 
services:
  db:
    image: postgres:15
    container_name: scheduler_db
    environment:
      POSTGRES_USER: tyler
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: scheduler_rx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: